### ISSUE TITLE
Shared view not found by exception handler middleware

### ISSUE THREAD

**Issue by Cobster** [aspnet/Diagnostics#249] opened 2016-02-17 18:32 UTC
The exception handler middleware is not finding the /Views/Shared/ServerError.cshtml.  Although the logs claim that the path is searched.

Scenario:

    [Route("api/[controller]")]
    public ValuesController : Controller
    {
        public IEnumerable<string> Get() 
        { 
            throw new NotImplementedException(); 
        }
    }

    public class ErrorController : Controller
    {
        [Route("Errors/ServerError")]
        public IActionResult Get() 
        {
            return View("ServerError");
        }
    }

    public class Startup
    {
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseIISPlatformHandler();
            app.UseExceptionHandler("/Errors/ServerError");
            app.UseStaticFiles();
            app.UseMvc();   
        }
    }

I also have the following view defined:

/Views/Shared/ServerError.cshtml

When a request is made to /api/values the following is logged:

    info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
          Executing action method WebApplication2.Controllers.ErrorsController.Get with arguments () - ModelState is Valid'
    fail: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[0]
           The view 'ServerError' was not found. Searched locations: /Views/Errors/ServerError.cshtml, /Views/Shared/ServerError.cshtml
    fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
          An exception was thrown attempting to execute the error handler.
          System.InvalidOperationException: The view 'ServerError' was not found. The following locations were searched:
          /Views/Errors/ServerError.cshtml
          /Views/Shared/ServerError.cshtml.

This works when a view is located at /View/Errors/ServerError.cshtml.  Just not the shared folder.

**Comment by Tratcher** [comment] 2016-02-17 18:35
Sounds like an MVC issue. @rynowak?

**Comment by kichalla** [comment] 2016-02-19 00:02
@Cobster I am unable to reproduce this issue. I used `rc1-final` packages. Which version are you using?

**Comment by Eaglef90** [comment] 2016-02-19 03:16
Hi @kichalla I orginally reported this over on SO (http://stackoverflow.com/questions/35231676/unhandled-expections-in-are-not-being-routed-to-my-custom-error-page) and @Cobster  posted it here as a bug. I am having the problem in rc1-final. I can post up a link to a project in the morning when I return the work and scrub the sensitive information form it if you need.

**Comment by Eaglef90** [comment] 2016-02-19 13:55
I have attached a copy of the project which also contains a screen cap of the error page produced when I go into debug mode form VS 2015. Please let me know what is wrong and why it is not working for me, and some others, but is working for you.

[JobSight - ASP Core -Broken.zip](https://github.com/aspnet/Diagnostics/files/138042/JobSight.-.ASP.Core.-Broken.zip)

**Comment by kichalla** [comment] 2016-02-19 17:32
Thanks for the repro and the snapshot. Based on what I have tried with the repro code and snapshot, I see (in debug) that an exception is being thrown during setup of EntityFramework services (related to connection string cannot be empty). Not sure if this is related to an error that happened while creating this repro. But I tried again by removing all the EF related stuff on the HomeController and was able to see the custom error view in the Shared folder.

**Comment by Eaglef90** [comment] 2016-02-19 19:17
In the project I am running has full connection strings I just removed it as it contains sensitive info. The error I am testing against is both a "throw new DivideByZeroException();" and taking the database offline so a SqlException error is thrown when EF can't connect to the database. If I run the project on my machine with the redacted connections string I do get an error in the Startup.cs which gives me the generic HTTP 500 error message. I will see if I can reproduce this on my home computer with another project this weekend.

**Comment by Eaglef90** [comment] 2016-02-22 18:36
Sorry but I was unable to test this over the weekend. I am hoping to do so Tonight/Tomorrow Night.

**Comment by kichalla** [comment] 2016-02-29 17:48
Closing this issue now. Feel free to reopen this issue with additional requested details.

**Closed by kichalla** 2016-02-29 17:48 UTC
Labels: 3 - Done, bug
