### ISSUE TITLE
UseStatusCodePagesWithRedirects does not work on Azure

### ISSUE THREAD

**Issue by Eilon** [aspnet/Diagnostics#361] opened 2017-04-19 21:20 UTC
_From @moraleslos on April 17, 2017 18:57_

Have an ASP.NET core app built using only RESTful services and an SPA built with React JS and client-side routing utilizing these services. In my startup I added this line:` app.UseStatusCodePagesWithRedirects("/");` to make sure that all status code errors go back to the root and hence loads the main index page.

This works great on localhost-- any url refresh or incorrect path entered in the browser will redirect to the main index page.  However when I deploy this exact app on Azure, it will not redirect.  Checking the console it essentially shows that it doesn't even redirect-- just tries to go to the url entered and gets a 404.  So, for example, if I did https://example.com/account and hit refresh, I expect it to redirect to https://example.com. However it just goes to https://example.com/account, hence get the standard error page _"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."_

Any ideas on how to resolve this issue on azure?

_Copied from original issue: aspnet/Mvc#6147_

**Comment by Eilon** [comment] 2017-06-06 17:21
@jbagga - can you investigate?

**Comment by jbagga** [comment] 2017-07-05 23:38
@moraleslos Can you share which version of the ASP.NET Core SDK you are using?

**Comment by jbagga** [comment] 2017-07-06 21:30
@moraleslos I tried publishing a simple app to Azure and am unable to reproduce with `2.0.0-preview2` SDK. Can you share more details or try the latest SDK? Let us know if you see the same behavior with 2.0.0-preview2.

**Comment by moraleslos** [comment] 2017-07-07 03:34
@jbagga I'm fairly certain it's currently 1.1.  I had this issue a while ago when using 1.0.  I won't be able to check until next week so if you could try 1.1 and see if it works for you that would be great.  If 1.1 works for you let me know too and I'll try to see why it won't work for us.  I can't upgrade to 2.0 until it's in a stable state.

**Comment by jbagga** [comment] 2017-07-07 17:48
@moraleslos I have verified that it works with 1.0 and 1.1 as well. It may be a something specific to your application.

**Comment by moraleslos** [comment] 2017-07-07 18:10
@jbagga Thanks!  Will take a look next week and will get back to you.

**Comment by jbagga** [comment] 2017-07-07 18:54
@moraleslos Closing for now but feel free to reopen it when you find out the underlying issue.

**Closed by jbagga** 2017-07-07 18:54 UTC
Labels: 2 - Working, investigate

**Comment by moraleslos** [comment] 2017-07-10 18:46
@jbagga 

Still doesn't work for me on Azure.  Below is my Configure method.

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                loggerFactory.AddConsole(Configuration.GetSection("Logging"));
                loggerFactory.AddDebug(LogLevel.Debug);

                app.UseCors(builder => builder
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowAnyOrigin()
                );
            }

            app.UseStatusCodePagesWithRedirects("/");

            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseOAuthValidation();
            app.UseOpenIddict();
            app.UseMvc();
}
```

Again works fine locally.  On azure, i just get a "Failed to load resource: the server responded with a status of 404 (Not Found)" written on the console log along with the "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." message.

TargetFramework: netcoreapp1.1

**Comment by jbagga** [comment] 2017-07-11 22:44
@moraleslos Are you able to share a sample app? I tried this Configure method but cannot repro the issue. Here is the sample I tried: https://github.com/jbagga/StatusCodePageRedirects

**Comment by moraleslos** [comment] 2017-07-13 16:39
I'm wondering if this issue has something to do with my app settings configuration on Azure.  For my "virtual applications and directories" configuration for my web app, I have these two set:

/ = site\wwwroot\wwwroot
/api = site\wwwroot

I had to do the above since my reactjs app was stored under wwwroot which was conflicting with my restful services (web api). 

Outside of this, seems like your example app and my config are almost identical.

**Comment by jbagga** [comment] 2017-07-17 18:27
@moraleslos I tried this as well and still cannot repro it. It may be something specific to your app. Feel free to share your app or modify mine to look like yours.
